wandb_version: 1

CLI-command:
  desc: null
  value: /home/dev/src/train.py --max-num-epochs 5 --max-files-per-dir 1 --dryrun
    --sequential --model ggnn2trans /trained_models ../resources/data/python/final/jsonl/train
    ../resources/data/python/final/jsonl/valid ../resources/data/python/final/jsonl/test
CUDA_VISIBLE_DEVICES:
  desc: null
  value: Not Set
_wandb:
  desc: null
  value:
    cli_version: 0.8.12
    is_jupyter_run: false
    python_version: 3.6.8
batch_size:
  desc: null
  value: 650
code_clamp_gradient_norm:
  desc: null
  value: 1.0
code_graph_activation_function:
  desc: null
  value: tanh
code_graph_dense_between_every_num_gnn_layers:
  desc: null
  value: 10000
code_graph_inter_layer_norm:
  desc: null
  value: false
code_graph_layer_input_dropout_keep_prob:
  desc: null
  value: 1.0
code_graph_model_activation_function:
  desc: null
  value: tanh
code_graph_num_layers:
  desc: null
  value: 8
code_graph_num_timesteps_per_layer:
  desc: null
  value: 1
code_graph_residual_connection_every_num_layers:
  desc: null
  value: 10000
code_graph_rnn_cell:
  desc: null
  value: GRU
code_hidden_size:
  desc: null
  value: 128
code_learning_rate:
  desc: null
  value: 0.001
code_learning_rate_decay:
  desc: null
  value: 0.98
code_lr_for_num_graphs_per_batch:
  desc: null
  value: null
code_mark_subtoken_end:
  desc: null
  value: false
code_max_epochs:
  desc: null
  value: 10000
code_max_nodes_in_batch:
  desc: null
  value: 50000
code_max_num_tokens:
  desc: null
  value: 200
code_message_aggregation_function:
  desc: null
  value: sum
code_momentum:
  desc: null
  value: 0.85
code_optimizer:
  desc: null
  value: Adam
code_patience:
  desc: null
  value: 25
code_random_seed:
  desc: null
  value: 0
code_use_subtokens:
  desc: null
  value: false
dropout_keep_rate:
  desc: null
  value: 0.9
fraction_using_func_name:
  desc: null
  value: 0.1
gradient_clip:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0005
learning_rate_code_scale_factor:
  desc: null
  value: 1.0
learning_rate_decay:
  desc: null
  value: 0.98
learning_rate_query_scale_factor:
  desc: null
  value: 1.0
loss:
  desc: null
  value: softmax
margin:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 5
min_len_func_name_for_query:
  desc: null
  value: 12
model-class:
  desc: null
  value: ggnn2trans
momentum:
  desc: null
  value: 0.85
optimizer:
  desc: null
  value: Adam
patience:
  desc: null
  value: 5
query_clamp_gradient_norm:
  desc: null
  value: 1.0
query_graph_activation_function:
  desc: null
  value: tanh
query_graph_dense_between_every_num_gnn_layers:
  desc: null
  value: 10000
query_graph_inter_layer_norm:
  desc: null
  value: false
query_graph_layer_input_dropout_keep_prob:
  desc: null
  value: 1.0
query_graph_model_activation_function:
  desc: null
  value: tanh
query_graph_num_layers:
  desc: null
  value: 8
query_graph_num_timesteps_per_layer:
  desc: null
  value: 1
query_graph_residual_connection_every_num_layers:
  desc: null
  value: 10000
query_graph_rnn_cell:
  desc: null
  value: GRU
query_hidden_size:
  desc: null
  value: 128
query_learning_rate:
  desc: null
  value: 0.001
query_learning_rate_decay:
  desc: null
  value: 0.98
query_lr_for_num_graphs_per_batch:
  desc: null
  value: null
query_max_epochs:
  desc: null
  value: 10000
query_max_nodes_in_batch:
  desc: null
  value: 50000
query_max_num_tokens:
  desc: null
  value: 30
query_message_aggregation_function:
  desc: null
  value: sum
query_momentum:
  desc: null
  value: 0.85
query_optimizer:
  desc: null
  value: Adam
query_patience:
  desc: null
  value: 25
query_random_seed:
  desc: null
  value: 0
query_random_token_frequency:
  desc: null
  value: 0.0
run-name:
  desc: null
  value: null
save_folder:
  desc: null
  value: /trained_models
seed:
  desc: null
  value: 0
test_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/test]'
train_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/train]'
valid_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/valid]'
