wandb_version: 1

CLI-command:
  desc: null
  value: /home/dev/src/train.py --testrun --dryrun --model convselfatt /trained_models
    ../resources/data/python/final/jsonl/train ../resources/data/python/final/jsonl/valid
    ../resources/data/python/final/jsonl/test
CUDA_VISIBLE_DEVICES:
  desc: null
  value: Not Set
_wandb:
  desc: null
  value:
    cli_version: 0.8.12
    is_jupyter_run: false
    python_version: 3.6.8
batch_size:
  desc: null
  value: 650
best_model_path:
  desc: null
  value: /trained_models/convselfatt-2019-10-18-21-27-57_model_best.pkl.gz
code_1dcnn_activation:
  desc: null
  value: tanh
code_1dcnn_add_residual_connections:
  desc: null
  value: true
code_1dcnn_kernel_width:
  desc: null
  value:
  - 8
  - 8
code_1dcnn_layer_list:
  desc: null
  value:
  - 128
  - 128
code_1dcnn_position_encoding:
  desc: null
  value: none
code_mark_subtoken_end:
  desc: null
  value: false
code_max_num_tokens:
  desc: null
  value: 200
code_pct_bpe:
  desc: null
  value: 0.5
code_self_attention_activation:
  desc: null
  value: gelu
code_self_attention_hidden_size:
  desc: null
  value: 128
code_self_attention_intermediate_size:
  desc: null
  value: 512
code_self_attention_num_heads:
  desc: null
  value: 8
code_self_attention_num_layers:
  desc: null
  value: 2
code_self_attention_pool_mode:
  desc: null
  value: weighted_mean
code_token_embedding_size:
  desc: null
  value: 128
code_token_vocab_count_threshold:
  desc: null
  value: 10
code_token_vocab_size:
  desc: null
  value: 10000
code_use_bpe:
  desc: null
  value: true
code_use_subtokens:
  desc: null
  value: false
dropout_keep_rate:
  desc: null
  value: 0.9
fraction_using_func_name:
  desc: null
  value: 0.1
gradient_clip:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0005
learning_rate_code_scale_factor:
  desc: null
  value: 1.0
learning_rate_decay:
  desc: null
  value: 0.98
learning_rate_query_scale_factor:
  desc: null
  value: 1.0
loss:
  desc: null
  value: softmax
margin:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 2
min_len_func_name_for_query:
  desc: null
  value: 12
model-class:
  desc: null
  value: convselfatt
momentum:
  desc: null
  value: 0.85
optimizer:
  desc: null
  value: Adam
patience:
  desc: null
  value: 5
query_1dcnn_activation:
  desc: null
  value: tanh
query_1dcnn_add_residual_connections:
  desc: null
  value: true
query_1dcnn_kernel_width:
  desc: null
  value:
  - 8
  - 8
query_1dcnn_layer_list:
  desc: null
  value:
  - 128
  - 128
query_1dcnn_position_encoding:
  desc: null
  value: none
query_mark_subtoken_end:
  desc: null
  value: false
query_max_num_tokens:
  desc: null
  value: 30
query_pct_bpe:
  desc: null
  value: 0.5
query_random_token_frequency:
  desc: null
  value: 0.0
query_self_attention_activation:
  desc: null
  value: gelu
query_self_attention_hidden_size:
  desc: null
  value: 128
query_self_attention_intermediate_size:
  desc: null
  value: 512
query_self_attention_num_heads:
  desc: null
  value: 8
query_self_attention_num_layers:
  desc: null
  value: 2
query_self_attention_pool_mode:
  desc: null
  value: weighted_mean
query_token_embedding_size:
  desc: null
  value: 128
query_token_vocab_count_threshold:
  desc: null
  value: 10
query_token_vocab_size:
  desc: null
  value: 10000
query_use_bpe:
  desc: null
  value: true
query_use_subtokens:
  desc: null
  value: false
run-name:
  desc: null
  value: null
save_folder:
  desc: null
  value: /trained_models
seed:
  desc: null
  value: 0
test_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/test]'
train_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/train]'
valid_folder:
  desc: null
  value: '[../resources/data/python/final/jsonl/valid]'
